# Generated by Django 3.2.4 on 2021-06-15 14:12

import core.utils.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='userbias',
            name='body_bias',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userbias',
            name='head_bias',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userbias',
            name='legs_bias',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userbias',
            name='user',
            field=core.utils.fields.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bias', to=settings.AUTH_USER_MODEL),
        ),
    ]
