# Generated by Django 3.2.4 on 2021-06-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='clothes',
            name='min_temperature',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clothes',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
