# Generated by Django 3.2.4 on 2021-06-15 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210615_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbias',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
