# Generated by Django 3.2.4 on 2021-06-15 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_userbias_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbias',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bias', to=settings.AUTH_USER_MODEL),
        ),
    ]
